# Generated by Django 4.0.1 on 2022-01-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_status_message_time_message_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='sender',
        ),
    ]
