# Generated by Django 4.0.1 on 2022-01-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_room_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
    ]
