# Generated by Django 4.0.1 on 2022-01-25 21:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_status_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 21, 55, 38, 307828, tzinfo=utc)),
        ),
    ]
