# Generated by Django 4.0.1 on 2022-04-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
