# Generated by Django 4.0.1 on 2022-11-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_delete_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='type',
            new_name='message_type',
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(blank=True, db_column='type', max_length=50, null=True),
        ),
    ]
