# Generated by Django 4.0.1 on 2023-02-22 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0014_alter_message_room_alter_participants_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='user',
        ),
        migrations.AddField(
            model_name='participants',
            name='users',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participants',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chat.room'),
        ),
    ]
