# Generated by Django 4.0.1 on 2023-03-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, choices=[('sent', 'Sent'), ('read', 'Read')], default='sent', max_length=20, null=True),
        ),
    ]
