# Generated by Django 4.0.1 on 2023-01-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_display_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_picture',
            field=models.ImageField(blank=True, default='profile_pictures/user-icon.png', upload_to='profile_pictures'),
        ),
    ]
