# Generated by Django 4.0.1 on 2023-01-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_display_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
