# Generated by Django 4.0.1 on 2023-03-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_friends', '0007_alter_friendrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
