# Generated by Django 4.0.1 on 2023-03-24 07:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('find_friends', '0008_friendrequest_seen'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='friendrequest',
            managers=[
                ('unseen_requests', django.db.models.manager.Manager()),
            ],
        ),
    ]
