# Generated by Django 4.0.1 on 2023-03-24 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_friends', '0009_alter_friendrequest_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='friendrequest',
            managers=[
            ],
        ),
    ]
